### ISSUE TITLE
Vendor dir breaks in Go 1.9 & Go 1.10

### ISSUE THREAD

**Issue by markbates** [shurcooL/highlight_go#1]
The latest commit, https://github.com/shurcooL/highlight_go/commit/3820d2d9b7c7afa0979ba0148cc306d9cc0b6d02, Breaks this package on Go 1.9 & Go 1.10

```bash
$ docker run -it golang:1.10 /bin/bash
$ go get github.com/shurcooL/highlight_go

# github.com/shurcooL/highlight_go/vendor/go/scanner
src/github.com/shurcooL/highlight_go/vendor/go/scanner/scanner.go:281:8: s.file.AddLineColumnInfo undefined (type *token.File has no field or method AddLineColumnInfo)
```

**Comment by dmitshur** [comment]
I see. Thank you for reporting @markbates. I'll work on a fix.

My [SLA](https://github.com/shurcooL/SLA#go-version) generally only covers current Go version, but this package is imported by `github_flavored_markdown`, which is used pretty widely, so I want it to work with older Go versions too.

**Comment by dmitshur** [comment]
This is resolved now. Please let me know if you run into any other issues.

**Comment by markbates** [comment]
Thanks!
