### ISSUE TITLE
unexpected = in type declaration

### ISSUE THREAD

**Issue by aduermael** [shurcooL/highlight_go#2]
When using `github.com/shurcooL/highlight_go` has a dependency, I get this build error: 

```
# website/vendor/github.com/shurcooL/highlight_go/internal/go/token
vendor/github.com/shurcooL/highlight_go/internal/go/token/token.go:12: syntax error: unexpected = in type declaration
```

It works if I use the previous commit: 98c3abbbae20a9fb3e3b218784855756b611656f

**Comment by dmitshur** [comment]
Thanks for reporting.

What version of Go are you using? I suspect it might be version Go 1.8 or older. If so, you'll need to update to Go 1.9 or newer, since that's when [type aliases](https://golang.org/doc/go1.9#language) were added.

**Comment by aduermael** [comment]
Oh, you're right. 
Sorry about that, I do have the latest version of Go installed on my machine, but it's been built in a container that has Go 1.8.3... 🤦‍♂️
Closing the issue!
